name: proje
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.0
  geolocator: ^13.0.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  http: ^1.3.0
  syncfusion_flutter_gauges: ^28.2.12
  fl_chart: ^0.40.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
